//! Linux integration: KDE (Dolphin) service menus with MIME scoping, GNOME
//! Nautilus scripts, and an XDG autostart entry.
//!
//! KDE: one `.desktop` file per source format under
//! `$XDG_DATA_HOME/kio/servicemenus/`, marked executable (required since
//! KF5.85) and scoped via `MimeType=` so only convertible files show the
//! Boinc submenu. `%F` passes all selected files, batch-converted by the CLI.
//!
//! Nautilus: scripts under `$XDG_DATA_HOME/nautilus/scripts/` (shown in the
//! "Scripts" submenu). Nautilus scripts cannot be MIME-scoped; unsupported
//! files fail gracefully with a notify-send message.

use std::io::Write as _;
use std::os::unix::fs::PermissionsExt as _;
use std::path::{Path, PathBuf};

use crate::entries::{MenuEntry, mime_type};

/// Grouped entries → one KDE service-menu file per source format.
pub fn kde_service_menu(
    dir: &Path,
    cli: &Path,
    from: boinc_core::Format,
    entries: &[MenuEntry],
) -> std::io::Result<PathBuf> {
    let actions: Vec<String> = entries.iter().map(MenuEntry::id).collect();
    let mut body = format!(
        "[Desktop Entry]\n\
         Type=Service\n\
         Name=Boinc\n\
         X-KDE-ServiceTypes=KonqPopupMenu/Plugin\n\
         MimeType={};\n\
         Actions={};\n\
         X-KDE-Submenu=Boinc\n",
        mime_type(from),
        actions.join(";"),
    );
    for entry in entries {
        body.push_str(&format!(
            "\n[Desktop Action {}]\nName={}\nIcon=document-export\nExec=\"{}\" convert --to {} %F\n",
            entry.id(),
            entry.label(),
            cli.display(),
            entry.to.extension(),
        ));
    }

    std::fs::create_dir_all(dir)?;
    let path = dir.join(format!("boinc-{}.desktop", from.extension()));
    write_executable(&path, &body)?;
    Ok(path)
}

/// One Nautilus script per conversion, batch-looping over the selection.
pub fn nautilus_script(dir: &Path, cli: &Path, entry: &MenuEntry) -> std::io::Result<PathBuf> {
    let body = format!(
        "#!/bin/sh\n\
         # Generated by Boinc (`boinc integrate uninstall` removes it).\n\
         printf '%s\\n' \"$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS\" | while IFS= read -r f; do\n\
         \x20 [ -n \"$f\" ] || continue\n\
         \x20 if ! \"{cli}\" convert \"$f\" --to {to}; then\n\
         \x20   command -v notify-send >/dev/null && notify-send 'Boinc' \"Could not convert $f\"\n\
         \x20 fi\n\
         done\n",
        cli = cli.display(),
        to = entry.to.extension(),
    );

    std::fs::create_dir_all(dir)?;
    let path = dir.join(format!(
        "{} to {} (Boinc)",
        entry.from.display_name(),
        entry.to.display_name()
    ));
    write_executable(&path, &body)?;
    Ok(path)
}

/// XDG autostart entry for the tray app.
pub fn autostart_file(dir: &Path, app: &Path) -> std::io::Result<PathBuf> {
    let body = format!(
        "[Desktop Entry]\n\
         Type=Application\n\
         Name=Boinc\n\
         Comment=Boinc file converter\n\
         Exec=\"{}\"\n\
         X-GNOME-Autostart-enabled=true\n",
        app.display(),
    );
    std::fs::create_dir_all(dir)?;
    let path = dir.join("boinc.desktop");
    let mut file = std::fs::File::create(&path)?;
    file.write_all(body.as_bytes())?;
    Ok(path)
}

fn write_executable(path: &Path, body: &str) -> std::io::Result<()> {
    let mut file = std::fs::File::create(path)?;
    file.write_all(body.as_bytes())?;
    let mut perms = file.metadata()?.permissions();
    perms.set_mode(0o755);
    std::fs::set_permissions(path, perms)
}

/// `$XDG_DATA_HOME/kio/servicemenus`
pub fn kde_dir() -> Option<PathBuf> {
    directories::BaseDirs::new().map(|b| b.data_dir().join("kio/servicemenus"))
}

/// `$XDG_DATA_HOME/nautilus/scripts`
pub fn nautilus_dir() -> Option<PathBuf> {
    directories::BaseDirs::new().map(|b| b.data_dir().join("nautilus/scripts"))
}

/// `$XDG_CONFIG_HOME/autostart`
pub fn autostart_dir() -> Option<PathBuf> {
    directories::BaseDirs::new().map(|b| b.config_dir().join("autostart"))
}

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod tests {
    use boinc_core::Format;

    use super::*;

    fn entry() -> MenuEntry {
        MenuEntry {
            from: Format::Png,
            to: Format::Jpg,
        }
    }

    #[test]
    fn kde_menu_is_mime_scoped_and_executable() {
        let dir = tempfile::tempdir().unwrap();
        let path = kde_service_menu(
            dir.path(),
            Path::new("/usr/bin/boinc"),
            Format::Png,
            &[entry()],
        )
        .unwrap();

        let body = std::fs::read_to_string(&path).unwrap();
        assert!(body.contains("MimeType=image/png;"));
        assert!(body.contains("X-KDE-Submenu=Boinc"));
        assert!(body.contains("Name=Convert to JPG"));
        assert!(body.contains("Exec=\"/usr/bin/boinc\" convert --to jpg %F"));

        let mode = std::fs::metadata(&path).unwrap().permissions().mode();
        assert_eq!(mode & 0o111, 0o111, "service menu must be executable");
    }

    #[test]
    fn nautilus_script_quotes_paths() {
        let dir = tempfile::tempdir().unwrap();
        let path = nautilus_script(dir.path(), Path::new("/usr/bin/boinc"), &entry()).unwrap();
        let body = std::fs::read_to_string(&path).unwrap();
        assert!(body.contains("convert \"$f\" --to jpg"));
        assert!(path.file_name().unwrap().to_str().unwrap() == "PNG to JPG (Boinc)");
    }

    #[test]
    fn autostart_entry_points_at_app() {
        let dir = tempfile::tempdir().unwrap();
        let path = autostart_file(dir.path(), Path::new("/opt/boinc/boinc-app")).unwrap();
        let body = std::fs::read_to_string(&path).unwrap();
        assert!(body.contains("Exec=\"/opt/boinc/boinc-app\""));
    }
}
