//! Linux integration: KDE (Dolphin) service menus with MIME scoping, GNOME
//! Nautilus scripts, Cinnamon (Nemo) actions, and an XDG autostart entry.
//!
//! KDE: one `.desktop` file per source format under
//! `$XDG_DATA_HOME/kio/servicemenus/`, marked executable (required since
//! KF5.85) and scoped via `MimeType=` so only convertible files show the
//! Boinc submenu. `%F` passes all selected files, batch-converted by the CLI.
//!
//! Nautilus: scripts under `$XDG_DATA_HOME/nautilus/scripts/` (shown in the
//! "Scripts" submenu). Nautilus scripts cannot be MIME-scoped; unsupported
//! files fail gracefully with a notify-send message.
//!
//! Nemo (Cinnamon): one `.nemo_action` per conversion under
//! `$XDG_DATA_HOME/nemo/actions/`, MIME-scoped via `Mimetypes=`. Nemo 6+
//! groups them under a **Boinc** submenu via
//! `$XDG_CONFIG_HOME/nemo/actions-tree.json` (the same layout file the
//! "Action layout editor" writes). Nemo watches both paths — usually no
//! restart needed; if the submenu does not appear, `nemo --quit` once.

use std::io::Write as _;
use std::os::unix::fs::PermissionsExt as _;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

use crate::entries::{MenuEntry, mime_type};

/// Filename of the Nemo action for one conversion (also the layout UUID).
pub fn nemo_action_filename(entry: &MenuEntry) -> String {
    format!("boinc-{}.nemo_action", entry.id())
}

/// Stable UUID / label for our Nemo submenu in `actions-tree.json`.
const NEMO_SUBMENU_UUID: &str = "Boinc";

/// Grouped entries → one KDE service-menu file per source format.
pub fn kde_service_menu(
    dir: &Path,
    cli: &Path,
    from: boinc_core::Format,
    entries: &[MenuEntry],
) -> std::io::Result<PathBuf> {
    let actions: Vec<String> = entries.iter().map(MenuEntry::id).collect();
    let mut body = format!(
        "[Desktop Entry]\n\
         Type=Service\n\
         Name=Boinc\n\
         X-KDE-ServiceTypes=KonqPopupMenu/Plugin\n\
         MimeType={};\n\
         Actions={};\n\
         X-KDE-Submenu=Boinc\n",
        mime_type(from),
        actions.join(";"),
    );
    for entry in entries {
        body.push_str(&format!(
            "\n[Desktop Action {}]\nName={}\nIcon=document-export\nExec=\"{}\" convert --app --to {} %F\n",
            entry.id(),
            entry.label(),
            cli.display(),
            entry.to.extension(),
        ));
    }

    std::fs::create_dir_all(dir)?;
    let path = dir.join(format!("boinc-{}.desktop", from.extension()));
    write_executable(&path, &body)?;
    Ok(path)
}

/// One Nautilus script per conversion, batch-looping over the selection.
pub fn nautilus_script(dir: &Path, cli: &Path, entry: &MenuEntry) -> std::io::Result<PathBuf> {
    let body = format!(
        "#!/bin/sh\n\
         # Generated by Boinc (`boinc integrate uninstall` removes it).\n\
         printf '%s\\n' \"$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS\" | while IFS= read -r f; do\n\
         \x20 [ -n \"$f\" ] || continue\n\
         \x20 if ! \"{cli}\" convert --app \"$f\" --to {to}; then\n\
         \x20   command -v notify-send >/dev/null && notify-send 'Boinc' \"Could not convert $f\"\n\
         \x20 fi\n\
         done\n",
        cli = cli.display(),
        to = entry.to.extension(),
    );

    std::fs::create_dir_all(dir)?;
    let path = dir.join(format!(
        "{} to {} (Boinc)",
        entry.from.display_name(),
        entry.to.display_name()
    ));
    write_executable(&path, &body)?;
    Ok(path)
}

/// One Nemo action per conversion, batch-capable via `%F`.
///
/// The label is just "Convert to …" — the parent **Boinc** submenu is provided
/// by [`sync_nemo_submenu`], not by stuffing "(Boinc)" into every name.
pub fn nemo_action(dir: &Path, cli: &Path, entry: &MenuEntry) -> std::io::Result<PathBuf> {
    let body = format!(
        "[Nemo Action]\n\
         Active=true\n\
         Name={label}\n\
         Comment=Convert the selected file(s) to {to} with Boinc\n\
         Exec=\"{cli}\" convert --app --to {to_ext} %F\n\
         Icon-Name=document-export\n\
         Selection=NotNone\n\
         Mimetypes={mime};\n",
        label = entry.label(),
        to = entry.to.display_name(),
        cli = cli.display(),
        to_ext = entry.to.extension(),
        mime = mime_type(entry.from),
    );

    std::fs::create_dir_all(dir)?;
    let path = dir.join(nemo_action_filename(entry));
    std::fs::write(&path, body)?;
    Ok(path)
}

// ---------------------------------------------------------------------------
// Nemo action layout (`actions-tree.json`) — groups our actions under "Boinc"
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Serialize, Deserialize)]
struct NemoLayout {
    toplevel: Vec<NemoLayoutNode>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct NemoLayoutNode {
    uuid: String,
    #[serde(rename = "type")]
    node_type: String,
    #[serde(
        rename = "user-label",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    user_label: Option<String>,
    #[serde(rename = "user-icon", default, skip_serializing_if = "Option::is_none")]
    user_icon: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    accelerator: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    children: Option<Vec<NemoLayoutNode>>,
}

fn is_boinc_action_uuid(uuid: &str) -> bool {
    uuid.starts_with("boinc-") && uuid.ends_with(".nemo_action")
}

fn is_boinc_submenu(node: &NemoLayoutNode) -> bool {
    node.node_type == "submenu"
        && (node.uuid == NEMO_SUBMENU_UUID || node.user_label.as_deref() == Some(NEMO_SUBMENU_UUID))
}

/// Drop any previous Boinc submenu or loose `boinc-*.nemo_action` nodes.
fn strip_boinc_nodes(nodes: Vec<NemoLayoutNode>) -> Vec<NemoLayoutNode> {
    nodes
        .into_iter()
        .filter_map(|mut node| {
            if is_boinc_submenu(&node) || is_boinc_action_uuid(&node.uuid) {
                return None;
            }
            if let Some(children) = node.children.take() {
                let kept = strip_boinc_nodes(children);
                node.children = if kept.is_empty() { None } else { Some(kept) };
            }
            Some(node)
        })
        .collect()
}

fn load_nemo_layout(path: &Path) -> NemoLayout {
    match std::fs::read_to_string(path) {
        Ok(text) => serde_json::from_str(&text).unwrap_or(NemoLayout {
            toplevel: Vec::new(),
        }),
        Err(_) => NemoLayout {
            toplevel: Vec::new(),
        },
    }
}

fn write_nemo_layout(path: &Path, layout: &NemoLayout) -> std::io::Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    let body = serde_json::to_string_pretty(layout)
        .map_err(|err| std::io::Error::new(std::io::ErrorKind::InvalidData, err))?;
    std::fs::write(path, body)
}

/// Ensure all current Boinc Nemo actions sit under a single **Boinc** submenu.
/// Merges into any existing user layout without wiping other custom entries.
pub fn sync_nemo_submenu(entries: &[MenuEntry]) -> std::io::Result<()> {
    let Some(path) = nemo_layout_path() else {
        return Ok(());
    };
    let mut layout = load_nemo_layout(&path);
    layout.toplevel = strip_boinc_nodes(layout.toplevel);

    let mut children: Vec<NemoLayoutNode> = entries
        .iter()
        .map(|entry| NemoLayoutNode {
            uuid: nemo_action_filename(entry),
            node_type: "action".into(),
            user_label: None,
            user_icon: None,
            accelerator: None,
            children: None,
        })
        .collect();
    // Stable order matches menu_entries (by from, then to).
    children.sort_by(|a, b| a.uuid.cmp(&b.uuid));

    if !children.is_empty() {
        layout.toplevel.insert(
            0,
            NemoLayoutNode {
                uuid: NEMO_SUBMENU_UUID.into(),
                node_type: "submenu".into(),
                user_label: Some(NEMO_SUBMENU_UUID.into()),
                user_icon: Some("document-export".into()),
                accelerator: None,
                children: Some(children),
            },
        );
    }

    write_nemo_layout(&path, &layout)
}

/// Remove the Boinc submenu from the Nemo layout (used on uninstall).
pub fn clear_nemo_submenu() -> std::io::Result<()> {
    let Some(path) = nemo_layout_path() else {
        return Ok(());
    };
    if !path.exists() {
        return Ok(());
    }
    let mut layout = load_nemo_layout(&path);
    let before = layout.toplevel.len();
    layout.toplevel = strip_boinc_nodes(layout.toplevel);
    if layout.toplevel.is_empty() && before > 0 {
        // Layout only had our stuff — delete the file so Nemo returns to
        // its default (flat) action ordering for everything else.
        match std::fs::remove_file(&path) {
            Err(err) if err.kind() != std::io::ErrorKind::NotFound => Err(err),
            _ => Ok(()),
        }
    } else if layout.toplevel.is_empty() {
        Ok(())
    } else {
        write_nemo_layout(&path, &layout)
    }
}

/// XDG autostart entry for the tray app.
pub fn autostart_file(dir: &Path, app: &Path) -> std::io::Result<PathBuf> {
    let body = format!(
        "[Desktop Entry]\n\
         Type=Application\n\
         Name=Boinc\n\
         Comment=Boinc file converter\n\
         Exec=\"{}\"\n\
         X-GNOME-Autostart-enabled=true\n",
        app.display(),
    );
    std::fs::create_dir_all(dir)?;
    let path = dir.join("boinc.desktop");
    let mut file = std::fs::File::create(&path)?;
    file.write_all(body.as_bytes())?;
    Ok(path)
}

fn write_executable(path: &Path, body: &str) -> std::io::Result<()> {
    let mut file = std::fs::File::create(path)?;
    file.write_all(body.as_bytes())?;
    let mut perms = file.metadata()?.permissions();
    perms.set_mode(0o755);
    std::fs::set_permissions(path, perms)
}

/// `$XDG_DATA_HOME/kio/servicemenus`
pub fn kde_dir() -> Option<PathBuf> {
    directories::BaseDirs::new().map(|b| b.data_dir().join("kio/servicemenus"))
}

/// `$XDG_DATA_HOME/nautilus/scripts`
pub fn nautilus_dir() -> Option<PathBuf> {
    directories::BaseDirs::new().map(|b| b.data_dir().join("nautilus/scripts"))
}

/// `$XDG_DATA_HOME/nemo/actions`
pub fn nemo_dir() -> Option<PathBuf> {
    directories::BaseDirs::new().map(|b| b.data_dir().join("nemo/actions"))
}

/// `$XDG_CONFIG_HOME/nemo/actions-tree.json` (Nemo 6+ action layout).
pub fn nemo_layout_path() -> Option<PathBuf> {
    directories::BaseDirs::new().map(|b| b.config_dir().join("nemo/actions-tree.json"))
}

/// `$XDG_CONFIG_HOME/autostart`
pub fn autostart_dir() -> Option<PathBuf> {
    directories::BaseDirs::new().map(|b| b.config_dir().join("autostart"))
}

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod tests {
    use boinc_core::Format;

    use super::*;

    fn entry() -> MenuEntry {
        MenuEntry {
            from: Format::Png,
            to: Format::Jpg,
        }
    }

    #[test]
    fn kde_menu_is_mime_scoped_and_executable() {
        let dir = tempfile::tempdir().unwrap();
        let path = kde_service_menu(
            dir.path(),
            Path::new("/usr/bin/boinc"),
            Format::Png,
            &[entry()],
        )
        .unwrap();

        let body = std::fs::read_to_string(&path).unwrap();
        assert!(body.contains("MimeType=image/png;"));
        assert!(body.contains("X-KDE-Submenu=Boinc"));
        assert!(body.contains("Name=Convert to JPG"));
        assert!(body.contains("Exec=\"/usr/bin/boinc\" convert --app --to jpg %F"));

        let mode = std::fs::metadata(&path).unwrap().permissions().mode();
        assert_eq!(mode & 0o111, 0o111, "service menu must be executable");
    }

    #[test]
    fn nautilus_script_quotes_paths() {
        let dir = tempfile::tempdir().unwrap();
        let path = nautilus_script(dir.path(), Path::new("/usr/bin/boinc"), &entry()).unwrap();
        let body = std::fs::read_to_string(&path).unwrap();
        assert!(body.contains("convert --app \"$f\" --to jpg"));
        assert!(path.file_name().unwrap().to_str().unwrap() == "PNG to JPG (Boinc)");
    }

    #[test]
    fn nemo_action_is_mime_scoped() {
        let dir = tempfile::tempdir().unwrap();
        let path = nemo_action(dir.path(), Path::new("/usr/bin/boinc"), &entry()).unwrap();
        assert_eq!(
            path.file_name().unwrap().to_str().unwrap(),
            "boinc-png-to-jpg.nemo_action"
        );
        let body = std::fs::read_to_string(&path).unwrap();
        assert!(body.starts_with("[Nemo Action]\n"));
        assert!(body.contains("Name=Convert to JPG\n"));
        assert!(!body.contains("(Boinc)"));
        assert!(body.contains("Exec=\"/usr/bin/boinc\" convert --app --to jpg %F"));
        assert!(body.contains("Mimetypes=image/png;"));
        assert!(body.contains("Selection=NotNone"));
    }

    #[test]
    fn nemo_layout_groups_actions_under_boinc_submenu() {
        let config = tempfile::tempdir().unwrap();
        // Point directories::BaseDirs at the sandbox via env — set for this
        // process only for the duration of the test helpers below by writing
        // the layout path directly instead (unit tests call strip/write with
        // explicit paths through the public merge helpers).
        let layout_path = config.path().join("nemo/actions-tree.json");

        // Seed a user layout with an unrelated custom action so we prove
        // merge (not overwrite).
        let seed = NemoLayout {
            toplevel: vec![NemoLayoutNode {
                uuid: "my-custom.nemo_action".into(),
                node_type: "action".into(),
                user_label: None,
                user_icon: None,
                accelerator: None,
                children: None,
            }],
        };
        write_nemo_layout(&layout_path, &seed).unwrap();

        let entries = [
            MenuEntry {
                from: Format::Png,
                to: Format::Jpg,
            },
            MenuEntry {
                from: Format::Png,
                to: Format::Svg,
            },
        ];

        // Simulate sync_nemo_submenu against this path.
        let mut layout = load_nemo_layout(&layout_path);
        layout.toplevel = strip_boinc_nodes(layout.toplevel);
        let children: Vec<_> = entries
            .iter()
            .map(|e| NemoLayoutNode {
                uuid: nemo_action_filename(e),
                node_type: "action".into(),
                user_label: None,
                user_icon: None,
                accelerator: None,
                children: None,
            })
            .collect();
        layout.toplevel.insert(
            0,
            NemoLayoutNode {
                uuid: NEMO_SUBMENU_UUID.into(),
                node_type: "submenu".into(),
                user_label: Some(NEMO_SUBMENU_UUID.into()),
                user_icon: Some("document-export".into()),
                accelerator: None,
                children: Some(children),
            },
        );
        write_nemo_layout(&layout_path, &layout).unwrap();

        let saved: NemoLayout =
            serde_json::from_str(&std::fs::read_to_string(&layout_path).unwrap()).unwrap();
        assert_eq!(saved.toplevel.len(), 2);
        assert_eq!(saved.toplevel[0].uuid, "Boinc");
        assert_eq!(saved.toplevel[0].node_type, "submenu");
        let kids = saved.toplevel[0].children.as_ref().unwrap();
        assert_eq!(kids.len(), 2);
        assert!(
            kids.iter()
                .any(|k| k.uuid == "boinc-png-to-jpg.nemo_action")
        );
        assert!(
            kids.iter()
                .any(|k| k.uuid == "boinc-png-to-svg.nemo_action")
        );
        assert_eq!(saved.toplevel[1].uuid, "my-custom.nemo_action");

        // Re-sync must not duplicate the Boinc submenu.
        layout = load_nemo_layout(&layout_path);
        layout.toplevel = strip_boinc_nodes(layout.toplevel);
        assert_eq!(layout.toplevel.len(), 1);
        assert_eq!(layout.toplevel[0].uuid, "my-custom.nemo_action");
    }

    #[test]
    fn autostart_entry_points_at_app() {
        let dir = tempfile::tempdir().unwrap();
        let path = autostart_file(dir.path(), Path::new("/opt/boinc/boinc-app")).unwrap();
        let body = std::fs::read_to_string(&path).unwrap();
        assert!(body.contains("Exec=\"/opt/boinc/boinc-app\""));
    }
}
