//! macOS integration: Finder Quick Actions (Services) as `.workflow`
//! bundles in `~/Library/Services`, scoped to the source format's UTI
//! (plan.md task 4.4), plus a LaunchAgent for launch-at-login.
//!
//! Each Quick Action is an Automator-format bundle containing a single
//! "Run Shell Script" action that batch-converts the selected files via the
//! CLI. Generated by template — Automator is not required.

use std::io;
use std::path::{Path, PathBuf};

use crate::entries::{MenuEntry, uti};

/// Create one Quick Action bundle; returns its path (for the manifest).
pub fn quick_action(services_dir: &Path, cli: &Path, entry: &MenuEntry) -> io::Result<PathBuf> {
    let name = format!("{} (Boinc).workflow", entry.label());
    let bundle = services_dir.join(&name);
    let contents = bundle.join("Contents");
    std::fs::create_dir_all(&contents)?;

    let display_name = format!("{} (Boinc)", entry.label());
    std::fs::write(
        contents.join("Info.plist"),
        info_plist(&display_name, uti(entry.from)),
    )?;
    std::fs::write(
        contents.join("document.wflow"),
        document_wflow(&shell_script(cli, entry)),
    )?;
    Ok(bundle)
}

/// LaunchAgent plist for launch-at-login.
pub fn launch_agent(agents_dir: &Path, app: &Path) -> io::Result<PathBuf> {
    std::fs::create_dir_all(agents_dir)?;
    let path = agents_dir.join("com.hideterms.boinc.plist");
    let body = format!(
        r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key><string>com.hideterms.boinc</string>
    <key>ProgramArguments</key><array><string>{}</string></array>
    <key>RunAtLoad</key><true/>
</dict>
</plist>
"#,
        xml_escape(&app.display().to_string())
    );
    std::fs::write(&path, body)?;
    Ok(path)
}

pub fn services_dir() -> Option<PathBuf> {
    directories::BaseDirs::new().map(|b| b.home_dir().join("Library/Services"))
}

pub fn launch_agents_dir() -> Option<PathBuf> {
    directories::BaseDirs::new().map(|b| b.home_dir().join("Library/LaunchAgents"))
}

fn shell_script(cli: &Path, entry: &MenuEntry) -> String {
    format!(
        "for f in \"$@\"; do \"{}\" convert \"$f\" --to {}; done",
        cli.display(),
        entry.to.extension()
    )
}

fn info_plist(display_name: &str, uti: &str) -> String {
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key><string>{name}</string>
    <key>NSServices</key>
    <array>
        <dict>
            <key>NSMenuItem</key><dict><key>default</key><string>{name}</string></dict>
            <key>NSMessage</key><string>runWorkflowAsService</string>
            <key>NSSendFileTypes</key><array><string>{uti}</string></array>
        </dict>
    </array>
</dict>
</plist>
"#,
        name = xml_escape(display_name),
        uti = uti,
    )
}

/// Automator document with a single "Run Shell Script" action receiving the
/// selection as arguments.
fn document_wflow(script: &str) -> String {
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>AMApplicationBuild</key><string>528</string>
    <key>AMApplicationVersion</key><string>2.10</string>
    <key>AMDocumentVersion</key><string>2</string>
    <key>actions</key>
    <array>
        <dict>
            <key>action</key>
            <dict>
                <key>AMActionVersion</key><string>2.0.3</string>
                <key>AMApplication</key><array><string>Automator</string></array>
                <key>AMParameterProperties</key><dict/>
                <key>ActionBundlePath</key><string>/System/Library/Automator/Run Shell Script.action</string>
                <key>ActionName</key><string>Run Shell Script</string>
                <key>ActionParameters</key>
                <dict>
                    <key>COMMAND_STRING</key><string>{script}</string>
                    <key>CheckedForUserDefaultShell</key><true/>
                    <key>inputMethod</key><integer>1</integer>
                    <key>shell</key><string>/bin/sh</string>
                    <key>source</key><string></string>
                </dict>
                <key>BundleIdentifier</key><string>com.apple.RunShellScript</string>
                <key>CFBundleVersion</key><string>2.0.3</string>
                <key>CanShowSelectedItemsWhenRun</key><false/>
                <key>CanShowWhenRun</key><true/>
                <key>Class Name</key><string>RunShellScriptAction</string>
                <key>InputUUID</key><string>6ID49E36-577F-4B67-9C08-C842DA5C4A28</string>
                <key>Keywords</key><array><string>Shell</string></array>
                <key>OutputUUID</key><string>7D96EC66-2FD5-4A21-BF1B-2AAF80C4E7AF</string>
                <key>UUID</key><string>2A1C41C1-C0EA-4E4B-B2E5-3F6A7E5F8C15</string>
                <key>isViewVisible</key><integer>1</integer>
            </dict>
        </dict>
    </array>
    <key>workflowMetaData</key>
    <dict>
        <key>serviceInputTypeIdentifier</key><string>com.apple.Automator.fileSystemObject</string>
        <key>serviceOutputTypeIdentifier</key><string>com.apple.Automator.nothing</string>
        <key>serviceProcessesInput</key><integer>0</integer>
        <key>workflowTypeIdentifier</key><string>com.apple.Automator.servicesMenu</string>
    </dict>
</dict>
</plist>
"#,
        script = xml_escape(script),
    )
}

fn xml_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}
